Remove outdated FFmpeg svn external, make configure optionally get and update a git checkout.
git-svn-id: svn://git.mplayerhq.hu/mplayer/trunk@32830 b3059339-0415-0410-9bf9-f77b7e298cf2

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -35,6 +35,29 @@
 #
 #############################################################################
 
+if test -e ffmpeg/.svn ; then
+  echo "You have an outdated FFmpeg SVN checkout in ffmpeg/, please (re)move or replace it"
+  exit 1
+fi
+
+if test -e ffmpeg/mp_auto_pull ; then
+  if ! (cd ffmpeg && git pull --rebase --ff-only) ; then
+    echo "git pull failed, (re)move ffmpeg/mp_auto_pull to disable pulling"
+    exit 1
+  fi
+fi
+
+if ! test -e ffmpeg ; then
+  echo "No FFmpeg checkout, press enter to download one with git or CTRL+C to abort"
+  read tmp
+  if ! git clone git://git.videolan.org/ffmpeg.git ffmpeg ; then
+    rm -rf ffmpeg
+    echo "Failed to get a FFmpeg checkout"
+    exit 1
+  fi
+  touch ffmpeg/mp_auto_pull
+fi
+
 # Prevent locale nonsense from breaking basic text processing utils
 export LC_ALL=C
 
