Refuse to compile without yasm unless it was explicitly requested.
git-svn-id: svn://git.mplayerhq.hu/mplayer/trunk@31793 b3059339-0415-0410-9bf9-f77b7e298cf2

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2721,7 +2721,9 @@ else
 fi
 
 echo "pabsw xmm0, xmm0" > $TMPS
-yasm_check || _yasm=""
+if test "$_yasm" ; then
+  yasm_check || die "yasm not found, use --yasm='' if you really want to compile without"
+fi
 if test $_yasm ; then
   def_yasm='#define HAVE_YASM 1'
   have_yasm="yes"
